### PR TITLE
form and functionality added

### PR DESCRIPTION
**Pull request by LevyMo**

### CODE REVIEW

**Comment by kiramiller425** [comment]
Hi Levy,
For assignment 14, there is one thing that need fixing:

In your JS file, this code:

```
    removeButton.addEventListener('click', function(event){
        let entry = removeButton.parentNode;
        entry.removeChild;
    });
```

needs to be fixed. As it is, the remove button will not actually remove the entry. You need to replace this: `removeButton.parentNode; `with the correct code.  `removeButton` is not what you need here. Hint: look at `event` instead.

Also, this won't work:
`        entry.removeChild;`
Remember, you want to remove the entry, not it's child.

Please make the changes above and resubmit your code. You're almost there!

**Comment by LevyMo** [comment]
Hi, Kira,
So in that code snippet:

 removeButton.addEventListener('click', function(event){
        let entry = removeButton.parentNode;
        entry.removeChild;
    });

I added ()'s and the code started working like this:

removeButton.addEventListener('click', function(event){
        let entry = removeButton.parentNode;
        entry.removeChild();
    });

Is that okay? Or do i need to still change it?

**Review by LevyMo — COMMENTED** [review]
remove button works now

**Comment by kiramiller425** [comment]
Great job, Levy! You're ready for the next lesson.

**Pull request merged**
